config:
  cognito:allow_admin_create_user_only: "false"
  cognito:callback_urls:
    - http://localhost:8080/api/auth/callback
  maive-infra:certificate_domain: localhost
  maive-infra:deploy_containers: "false"
  maive-infra:environment: dev
  maive-infra:transport_protocol: http
  s3:force_destroy: "true"