config:
  maive-infra:environment: staging
  maive-infra:certificate_domain: staging.maive.ai
  maive-infra:deploy_containers: "true"
  maive-infra:transport_protocol: https
  cognito:callback_urls:
    - https://staging.maive.ai/api/auth/callback
    - http://localhost:8080/api/auth/callback