"""create call list table

Revision ID: d1589b6ca2c7
Revises: ba8c60a76780
Create Date: 2025-10-27 14:59:45.382567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1589b6ca2c7'
down_revision: Union[str, Sequence[str], None] = 'ba8c60a76780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_list_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='User ID (sub)'),
    sa.Column('project_id', sa.String(length=255), nullable=False, comment='Project/Job ID from CRM'),
    sa.Column('call_completed', sa.Boolean(), nullable=False, comment='Whether the call for this project has been completed'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Position in the call list for ordering'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_user_project')
    )
    op.create_index('idx_user_position', 'call_list_items', ['user_id', 'position'], unique=False)
    op.create_index(op.f('ix_call_list_items_project_id'), 'call_list_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_call_list_items_user_id'), 'call_list_items', ['user_id'], unique=False)
    op.drop_constraint(op.f('calls_call_id_key'), 'calls', type_='unique')
    op.drop_index(op.f('ix_calls_call_id'), table_name='calls')
    op.create_index(op.f('ix_calls_call_id'), 'calls', ['call_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_call_id'), table_name='calls')
    op.create_index(op.f('ix_calls_call_id'), 'calls', ['call_id'], unique=False)
    op.create_unique_constraint(op.f('calls_call_id_key'), 'calls', ['call_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_call_list_items_user_id'), table_name='call_list_items')
    op.drop_index(op.f('ix_call_list_items_project_id'), table_name='call_list_items')
    op.drop_index('idx_user_position', table_name='call_list_items')
    op.drop_table('call_list_items')
    # ### end Alembic commands ###
