[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

[dependency-groups]
rilla = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "tqdm>=4.67.1",
]
